# Generated by Django 2.0.1 on 2018-01-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('bank_id', models.SmallIntegerField(default=0, verbose_name='银行ID')),
                ('card_number', models.CharField(default='', max_length=30, unique=True, verbose_name='银行卡号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '绑定银行卡',
                'verbose_name_plural': '绑定银行卡',
                'db_table': 'core_auth_card',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True, verbose_name='银行名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '银行信息',
                'verbose_name_plural': '银行信息',
                'db_table': 'core_bank',
            },
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('bank_id', models.SmallIntegerField(default=0, verbose_name='银行ID')),
                ('card_number', models.CharField(default='', max_length=30, unique=True, verbose_name='银行卡号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '提现银行卡',
                'verbose_name_plural': '提现银行卡',
                'db_table': 'core_bank_card',
            },
        ),
        migrations.CreateModel(
            name='CreditAssignProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0, verbose_name='原项目ID')),
                ('invest_id', models.IntegerField(default=0, verbose_name='投资ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='总金额')),
                ('invested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='已投金额')),
                ('end_at', models.DateField(auto_now_add=True, verbose_name='项目完结日')),
                ('status', models.SmallIntegerField(default=100, verbose_name='项目状态')),
                ('serial_number', models.IntegerField(default=0, verbose_name='每天不重复的编号')),
                ('app_type', models.SmallIntegerField(verbose_name='App来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '债权项目',
                'verbose_name_plural': '债权项目',
                'db_table': 'core_credit_assign_project',
            },
        ),
        migrations.CreateModel(
            name='CurrentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='账户总金额')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='总利息')),
                ('yesterday_interest', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='昨日利息')),
                ('interested_at', models.DateTimeField(auto_now_add=True, verbose_name='计算日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '活期账户',
                'verbose_name_plural': '活期账户',
                'db_table': 'core_current_account',
            },
        ),
        migrations.CreateModel(
            name='CurrentInterestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='利率')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='利息')),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='本息')),
                ('interest_date', models.DateField(auto_now_add=True, verbose_name='计算日期')),
                ('type', models.SmallIntegerField(default=1, verbose_name='利息来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '活期收益记录',
                'verbose_name_plural': '活期收益记录',
                'db_table': 'core_current_interest_history',
            },
        ),
        migrations.CreateModel(
            name='CurrentPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, unique=True, verbose_name='用户ID')),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='截止今日0点的活期账户金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '活期待收',
                'verbose_name_plural': '活期待收',
                'db_table': 'core_current_principal',
            },
        ),
        migrations.CreateModel(
            name='FundHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='变更前金额')),
                ('balance_change', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='变更额')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='变更后金额')),
                ('event_id', models.SmallIntegerField(default=1, verbose_name='事件id')),
                ('note', models.CharField(default='', max_length=100, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资金流水',
                'verbose_name_plural': '资金流水',
                'db_table': 'core_fund_history',
            },
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0, verbose_name='项目ID')),
                ('assign_project_id', models.IntegerField(default=0, verbose_name='债转项目ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='投资金额')),
                ('invested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='已投金额')),
                ('is_match', models.SmallIntegerField(default=100, verbose_name='是否匹配')),
                ('invest_type', models.SmallIntegerField(default=0, verbose_name='投资来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '投资记录',
                'verbose_name_plural': '投资记录',
                'db_table': 'core_invest',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=32, unique=True, verbose_name='订单编号')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='金额')),
                ('handling_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='手续费')),
                ('status', models.SmallIntegerField(default=300, verbose_name='订单状态')),
                ('success_time', models.DateTimeField(verbose_name='处理成功时间')),
                ('type', models.SmallIntegerField(default=1, verbose_name='订单状态')),
                ('random', models.CharField(default='0', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'core_order',
            },
        ),
        migrations.CreateModel(
            name='OrderExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=32, unique=True, verbose_name='订单编号')),
                ('bank_id', models.SmallIntegerField(default=0, verbose_name='银行ID')),
                ('card_number', models.CharField(default='', max_length=30, unique=True, verbose_name='银行卡号')),
                ('trade_no', models.CharField(default='', max_length=30, unique=True, verbose_name='交易流水号')),
                ('type', models.SmallIntegerField(default=0, verbose_name='支付渠道')),
                ('note', models.CharField(default='', max_length=200, verbose_name='订单备信息')),
                ('app_request', models.SmallIntegerField(default='', verbose_name='三端来源')),
                ('abnormal', models.BooleanField(default=0, verbose_name='账户资金流水是否异')),
                ('app_type', models.SmallIntegerField(verbose_name='App来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '订单扩展表',
                'verbose_name_plural': '订单扩展表',
                'db_table': 'core_order_extend',
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0, verbose_name='项目ID')),
                ('invest_id', models.IntegerField(default=0, verbose_name='投资ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='本金')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='总利息')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='本息')),
                ('times', models.DateField(verbose_name='还款日')),
                ('status', models.SmallIntegerField(default=300, verbose_name='还款状态')),
                ('before_refund', models.SmallIntegerField(default=0, verbose_name='是否提前还款')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户回款记录表',
                'verbose_name_plural': '用户回款记录表',
                'db_table': 'core_refund_record',
            },
        ),
        migrations.CreateModel(
            name='TermPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, unique=True, verbose_name='用户ID')),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='截止今日0点的定期待收本金')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '定期待收',
                'verbose_name_plural': '定期待收',
                'db_table': 'core_term_principal',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=11, unique=True, verbose_name='手机号')),
                ('password_hash', models.CharField(default='', max_length=65, verbose_name='密码')),
                ('trading_password', models.CharField(default='', max_length=65, verbose_name='交易密码')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='账户余额')),
                ('status_code', models.SmallIntegerField(default=200, verbose_name='用户状态')),
                ('real_name', models.CharField(default='', max_length=30, verbose_name='姓名')),
                ('identity_card', models.CharField(default='', max_length=25, verbose_name='身份证号')),
                ('note', models.CharField(default='', max_length=50, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户列表',
                'verbose_name_plural': '用户列表',
                'db_table': 'core_user',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['identity_card'], name='idx_identity_card'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['user_id'], name='idx_user_id'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['times'], name='idx_times'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['project_id'], name='idx_project_id'),
        ),
        migrations.AddIndex(
            model_name='orderextend',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id'], name='idx_user_id'),
        ),
        migrations.AddIndex(
            model_name='invest',
            index=models.Index(fields=['project_id'], name='idx_project_id'),
        ),
        migrations.AddIndex(
            model_name='invest',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='invest',
            index=models.Index(fields=['user_id'], name='idx_user_id'),
        ),
        migrations.AddIndex(
            model_name='invest',
            index=models.Index(fields=['assign_project_id'], name='idx_assign_project_id'),
        ),
        migrations.AddIndex(
            model_name='fundhistory',
            index=models.Index(fields=['user_id', 'event_id'], name='idx_user_event'),
        ),
        migrations.AddIndex(
            model_name='fundhistory',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='currentinteresthistory',
            index=models.Index(fields=['user_id', 'interest_date', 'type'], name='idx_user_date_type'),
        ),
        migrations.AddIndex(
            model_name='currentinteresthistory',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='currentaccount',
            index=models.Index(fields=['user_id'], name='idx_user_id'),
        ),
        migrations.AddIndex(
            model_name='creditassignproject',
            index=models.Index(fields=['project_id'], name='idx_project_id'),
        ),
        migrations.AddIndex(
            model_name='creditassignproject',
            index=models.Index(fields=['invest_id'], name='idx_invest_id'),
        ),
        migrations.AddIndex(
            model_name='creditassignproject',
            index=models.Index(fields=['user_id'], name='idx_user_id'),
        ),
        migrations.AddIndex(
            model_name='bankcard',
            index=models.Index(fields=['user_id'], name='idx_user_id'),
        ),
        migrations.AddIndex(
            model_name='authcard',
            index=models.Index(fields=['user_id'], name='idx_user_id'),
        ),
    ]
