# Generated by Django 2.0.1 on 2018-01-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiudouyu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthCard',
        ),
    ]
