# Generated by Django 2.0.1 on 2018-01-22 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISBN',
            new_name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.IntegerField(default=0, verbose_name='分类ID'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, verbose_name='书箱页数'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='出版日期'),
            preserve_default=False,
        ),
    ]
